todo/todo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todoapp/',include('todoapp.urls')),
]

todo/todoapp/urls.py
from django.conf.urls import url
#from django.contrib import admin
from todoapp import views 
app_name = 'todoapp'

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view(),name='index'),
    # todoapp/1
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    
]

todo/todoapp/models.py
from django.db import models

# Create your models here.


class Task(models.Model):

    def __str__(self):
        return self.task_name

    task_name = models.CharField(max_length=200)
    task_priority= models.CharField(max_length=200)

todo/todoapp/views.py
from django.views import generic
from .models import Task


class IndexView(generic.ListView):
    template_name = 'todoapp/index.html'

    def get_queryset(self):
        return Task.objects.all()


class DetailView(generic.DetailView):
            model = Task
            template_name = 'todoapp/detail.html'

todo/todoapp/templates/todoapp/base.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'todoapp/style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                     <a class="navbar-brand" href="#">TodoApp</a>
                </div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Item 1</a></li>
                    <li><a href="#">item 2</a></li>
                    <li><a href="#">item 3</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="#">Item 1</a></li>
                    <li><a href="#">item 2</a></li>
                    <li><a href="#">item 3</a></li>
                </ul>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

todo/todoapp/templates/todoapp/detail.html
{% extends 'todoapp/base.html' %}
{% block body %}
       
{{task.task_name}}</br>
{{task.task_priority}}

{% endblock %}

todo/todoapp/templates/todoapp/index.html
{% extends 'todoapp/base.html' %}

<html>
    <head>

        
    </head>
    <body>

      {% block body %}
      

         <div class="container">
             <h2>Todays list</h2>
             <p>Lets get things done</p>
             <table class="table">
                 <thead>
                     <tr>
                         <th>Task Name</th>
                         <th>Task Priority</th>
                         <th>Action</th>
                     </tr>
                 </thead>

                 <tbody>
                    {% if task_list %}
                       {% for task in object_list %} 
                       <tr class="active">
                           <td> <a href="{% url 'todoapp:detail' task.id %}">{{task.task_name}}</a> </td>
                           <td><b>{{task.task_priority}}</b></td>
                           <td><button type="submit" class="btn btn-success">Done</button></td>
                       </tr>
                    {% endfor %}
                    {% endif %}
                       
                       
                          
                           
                           
                       
                       
                       
                       
                </tbody>
             </table>
         </div>
         {% endblock %}
    </body>
</html>